# Generated by Django 3.2.7 on 2021-09-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseNo',
            fields=[
                ('timedatemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdata.timedatemixin')),
                ('number', models.CharField(max_length=250)),
            ],
            bases=('userdata.timedatemixin',),
        ),
    ]
