# Generated by Django 3.2.7 on 2021-09-27 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0002_auto_20210927_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('s_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skey_g', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('timedatemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdata.timedatemixin')),
                ('guest_name', models.CharField(max_length=300)),
                ('purpose', models.TextField()),
                ('guestcategory_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mkey', to='execution.guestcategory')),
                ('house_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gkey', to='execution.houseno')),
                ('user_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgkey', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('userdata.timedatemixin',),
        ),
    ]
