# Generated by Django 3.2.7 on 2021-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_guest_total_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
