# Generated by Django 3.2.7 on 2021-09-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_alter_guest_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='mobile_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
