# Generated by Django 3.2.7 on 2021-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_guest_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseno',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
