# Generated by Django 3.2.7 on 2021-09-29 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0008_auto_20210928_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='special_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specikey', to=settings.AUTH_USER_MODEL),
        ),
    ]
