# Generated by Django 3.2.7 on 2021-09-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_guest_special_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseno',
            name='member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
