# Generated by Django 3.2.7 on 2021-09-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0011_alter_member_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
