# Generated by Django 3.2.7 on 2021-10-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0013_member_is_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ('-create_at',)},
        ),
    ]
